<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('menu_items')->delete();

        \DB::table('menu_items')->insert(array(
            0 =>
            array(
                'id' => 2,
                'slug' => 'deti_7_11_let',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Дети (7-11 лет)", "lv" => "Bērni (7-11 gadi)"]),
                'description' => json_encode(["ru" => "Мы организуем различные мероприятия для детей.", "lv" => "Mēs organizējam dažādus pasākumus bērniem."]),
                'params' => NULL,
                'sort_order' => 3,
                '_lft' => 36,
                '_rgt' => 47,
                'parent_id' => 23,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:40:20',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            1 =>
            array(
                'id' => 3,
                'slug' => 'podrostki_12_15_let',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Подростки (12-15 лет)", "lv" => "Jaunieši (12-15 gadi)"]),
                'description' => json_encode(["ru" => "Мы организуем различные мероприятия для подростков.", "lv" => "Mēs organizējam dažādus pasākumus jauniešiem."]),
                'params' => NULL,
                'sort_order' => 2,
                '_lft' => 22,
                '_rgt' => 35,
                'parent_id' => 23,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:40:45',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            2 =>
            array(
                'id' => 4,
                'slug' => 'molodezh_16_let',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Молодежь (16+ лет)", "lv" => "Jaunieši (16+ gadi)"]),
                'description' => json_encode(["ru" => "16+", "lv" => "16+"]),
                'params' => NULL,
                'sort_order' => 1,
                '_lft' => 48,
                '_rgt' => 59,
                'parent_id' => 23,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:40:57',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            3 =>
            array(
                'id' => 5,
                'slug' => 'drugoe',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Другое", "lv" => "Cits"]),
                'description' => json_encode(["ru" => "Описание отсутствует.", "lv" => "Apraksts nav pieejams."]),
                'params' => NULL,
                'sort_order' => 0,
                '_lft' => 2,
                '_rgt' => 21,
                'parent_id' => 23,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:41:06',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            4 =>
            array(
                'id' => 6,
                'slug' => 'vyezdnye_lagerya',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Выездные лагеря", "lv" => "Izbraukuma nometnes"]),
                'description' => json_encode(["ru" => "Если хотите получать информацию о предстоящих выездных лагерях, заполняйте анкету: \r\nhttps://ej.uz/vijezdnielagerja", "lv" => "Ja vēlaties saņemt informāciju par nākamajām izbraukuma nometnēm, aizpildiet anketu: \r\nhttps://ej.uz/izbraukumanometnes"]),
                'params' => NULL,
                'sort_order' => 0,
                '_lft' => 37,
                '_rgt' => 38,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:57:48',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            5 =>
            array(
                'id' => 7,
                'slug' => 'letnyaya_shkola',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Летняя школа", "lv" => "Vasaras skola"]),
                'description' => json_encode(["ru" => "На каникулах мы устраиваем летнюю школу для детей 7-11 лет. Это отличная возможность интересно и весело провести каникулы, а также найти новых друзей. Вместе мы ходим на экскурсии, участвуем в мастер-классах, занимаемся спортом и гуляем.", "lv" => "Brīvlaikos mēs rīkojam vasaras skolu bērniem no 7 līdz 11 gadiem. Tas ir lielisks veids, kā interesanti un jautri pavadīt brīvlaiku, kā arī atrast jaunus draugus. Kopā mēs dodamies ekskursijās, piedalāmies meistarklasēs, nodarbojamies ar sportu un pastaigājamies."]),
                'params' => NULL,
                'sort_order' => 1,
                '_lft' => 39,
                '_rgt' => 40,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:59:20',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            6 =>
            array(
                'id' => 8,
                'slug' => 'zanyatiya',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Занятия", "lv" => "Nodarbības"]),
                'description' => json_encode(["ru" => "В Young Folks часто проходят платные занятия и мастер-классы под руководством воспитателей, учителей и тренеров. \r\n\r\nЕсли хотите получать информацию о различных занятиях и мастер-классах, заполняйте анкету: \r\nhttps://ej.uz/zanjatija", "lv" => "Young Folks bieži piedāvā maksas nodarbības un meistarklases, ko vada audzinātāji, skolotāji un treneri. \r\n\r\nJa vēlaties saņemt informāciju par dažādām nodarbībām un meistarklasēm, aizpildiet anketu: \r\nhttps://ej.uz/zanjatija"]),
                'params' => NULL,
                'sort_order' => 2,
                '_lft' => 41,
                '_rgt' => 42,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 19:59:29',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            7 =>
            array(
                'id' => 9,
                'slug' => 'master_klassy',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Мастер-классы", "lv" => "Meistarklases"]),
                'description' => json_encode(["ru" => "Добавить описание", "lv" => "Pievienot aprakstu"]),
                'params' => NULL,
                'sort_order' => 3,
                '_lft' => 43,
                '_rgt' => 44,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:00:09',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            8 =>
            array(
                'id' => 10,
                'slug' => 'organizaciya_detskih',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Организация детских праздников", "lv" => "Bērnu svētku organizēšana"]),
                'description' => json_encode(["ru" => "Хотите подарить детям незабываемый День рождения? Мы поможем вам с организацией и проведением вашего праздника. \r\n\r\nhttps://ej.uz/kidsevents", "lv" => "Vai vēlaties piedāvāt bērniem neaizmirstamu dzimšanas dienu? Mēs jums palīdzēsim ar pasākuma organizēšanu un tā norisi. \r\n\r\nhttps://ej.uz/kidsevents"]),
                'params' => NULL,
                'sort_order' => 4,
                '_lft' => 45,
                '_rgt' => 46,
                'parent_id' => 2,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:00:24',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            9 =>
            array(
                'id' => 11,
                'slug' => 'intensivy_vyezdy',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" =>  "Интенсивы, выезды, лагеря", "lv" =>  "Intensīvie, braucieni, nometnes"]),
                'description' => json_encode(["ru" =>  "Как насчёт отправиться в кемпинг с ночными посиделками и гитарой у костра? \\\\r\\\\n\\\\r\\\\nЕсли хотите получить информацию о предстоящих выездах, лагерях и интенсивах, заполните анкету:\\\\r\\\\nhttps://ej.uz/lagerjaYF", "lv" => "Kā būtu izbraukt uz intensīvām nodarbībām, braucieniem un nometnēm? \\\\r\\\\n\\\\r\\\\nJa vēlaties saņemt informāciju par gaidāmajiem braucieniem, nometnēm un intensīvām nodarbībām, aizpildiet anketu:\\\\r\\\\nhttps://ej.uz/lagerjaYF"]),
                'params' => NULL,
                'sort_order' => 0,
                '_lft' => 23,
                '_rgt' => 24,
                'parent_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:02:47',
                'updated_at' => '2023-03-06 21:21:05',
            ),
            10 =>
            array(
                'id' => 12,
                'slug' => 'kursy_platnye',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" =>  "Курсы, платные занятия", "lv" => "Maksas kursi, nodarbības"]),
                'description' => json_encode(["ru" => "В Young Folks часто проходят платные курсы под руководством учителей, тренеров и коучев.\\\\r\\\\nЕсли хотите получить информацию о различных курсах, заполните анкету:\\\\r\\\\nhttps://ej.uz/kursiYF", "lv" => "Young Folks bieži piedāvā maksas kursus, kas tiek vadīti ar skolotāju, treneru un kouču palīdzību.\\\\r\\\\nJa vēlaties saņemt informāciju par dažādiem kursiem, aizpildiet anketu:\\\\r\\\\nhttps://ej.uz/kursiYF"]),
                'params' => NULL,
                'sort_order' => 1,
                '_lft' => 25,
                '_rgt' => 26,
                'parent_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:03:07',
                'updated_at' => '2023-03-06 21:21:09',
            ),
            11 =>
            array(
                'id' => 13,
                'slug' => 'klub_podrostkov',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Клуб подростков", "lv" => "Jauniešu klubs"]),
                'description' => json_encode(["ru" => "Это образовательная среда для подростков и молодежи, где можно найти себе друзей, кружки по интересам, также стать лидером, реализовать свой проект и проводить свободное время с пользой.\r\n\r\nВступить в клуб: http://www.youngfolks.lv/Ru/club", "lv" => "Tas ir izglītojošs vidējs jauniešiem un jauniešiem, kur var atrast draugus, interesējošās pulciņus, kļūt par līderi, realizēt savu projektu un pavadīt brīvo laiku ar labumu.\r\n\r\nIestāties klubā: http://www.youngfolks.lv/Ru/club"]),
                'params' => NULL,
                'sort_order' => 2,
                '_lft' => 27,
                '_rgt' => 30,
                'parent_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:03:33',
                'updated_at' => '2023-03-07 02:00:00',
            ),
            12 =>
            array(
                'id' => 14,
                'slug' => 'kursy_zanyatiya',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Курсы, занятия", "lv" => "Kursi, nodarbības"]),
                'description' => json_encode(["ru" => "В Young Folks часто проходят платные курсы под руководством учителей, тренеров и коучев. \r\n\r\nЕсли хотите получать информацию о различных курсах и занятиях, заполняйте анкету: \r\nhttps://ej.uz/kursiYF", "lv" => "Young Folks bieži organizē maksas kursus, kuru vadītāji ir skolotāji, treneri un kouči. \r\n\r\nJa vēlaties saņemt informāciju par dažādiem kursiem un nodarbībām, aizpildiet anketu: \r\nhttps://ej.uz/kursiYF"]),
                'params' => NULL,
                'sort_order' => 0,
                '_lft' => 49,
                '_rgt' => 50,
                'parent_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:03:58',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            13 =>
            array(
                'id' => 15,
                'slug' => 'klub_young_folks_1',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Клуб Young Folks для молодежи.", "lv" => "Jauniešu klubs Young Folks."]),
                'description' => json_encode(["ru" => "Это образовательная среда для подростков и молодежи, где можно найти себе друзей, кружки по интересам, также стать лидером, реализовать свой проект и проводить свободное время с пользой.\r\n\r\nВступить в клуб: https://ej.uz/youngfolkslv_youth", "lv" => "Young Folks klubs jauniešiem. Izglītojoša vide, kur var atrast jaunus draugus, intereses pulciņus, kļūt par līderi, realizēt savu projektu un pavadīt brīvo laiku ar labumu.\r\n\r\nPievienoties klubam: https://ej.uz/youngfolkslv_youth"]),
                'params' => NULL,
                'sort_order' => 12,
                '_lft' => 51,
                '_rgt' => 52,
                'parent_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:04:09',
                'updated_at' => '2023-03-07 12:33:03',
            ),
            14 =>
            array(
                'id' => 16,
                'slug' => 'erasmus',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Erasmus+", "lv" => "Erasmus+"]),
                'description' => json_encode(["ru" => "Erasmus+ написание проектов\r\n\r\nhttps://forms.gle/1KVQ6CYpsKu9f8bD8", "lv" => "Erasmus+ projektu rakstīšana\r\n\r\nhttps://forms.gle/1KVQ6CYpsKu9f8bD8"]),
                'params' => NULL,
                'sort_order' => 13,
                '_lft' => 55,
                '_rgt' => 56,
                'parent_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:04:23',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            15 =>
            array(
                'id' => 17,
                'slug' => 'pomoshch_bezhencam',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Помощь беженцам", "lv" => "Bēgļu palīdzība"]),
                'description' => json_encode(["ru" => "Add description", "lv" => "Pievienot aprakstu"]),
                'params' => NULL,
                'sort_order' => 14,
                '_lft' => 3,
                '_rgt' => 4,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:04:56',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            16 =>
            array(
                'id' => 18,
                'slug' => 'young_works',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Young Works", "lv" => "Young Works"]),
                'description' => json_encode(["ru" => "Young works - платформа по поиску специалистов среди молодёжи Young Folks.\r\nhttps://youngfolks.lv/youngworks", "lv" => "Young works – platforma jauniešu Young Folks vidū, kas meklē speciālistus.\r\nhttps://youngfolks.lv/youngworks"]),
                'params' => NULL,
                'sort_order' => 15,
                '_lft' => 5,
                '_rgt' => 6,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:05:07',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            17 =>
            array(
                'id' => 19,
                'slug' => 'sayit_ring',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Sayit.ring", "lv" => "Sayit.ring"]),
                'description' => json_encode(["ru" => "Sayit.ring - изготовление колец и браслетов с вашей уникальной гравировкой.\r\nhttps://youngfolks.lv/ru/ring", "lv" => "Sayit.ring – gredzenu un aproču izgatavošana ar jūsu unikālo gravējumu.\r\nhttps://youngfolks.lv/ru/ring"]),
                'params' => NULL,
                'sort_order' => 16,
                '_lft' => 7,
                '_rgt' => 8,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:05:29',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            18 =>
            array(
                'id' => 20,
                'slug' => 'kekstarter',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Kekstarter", "lv" => "Kekstarter"]),
                'description' => json_encode(["ru" => "Kekstarter - краундфаундинговая платформа", "lv" => "Kekstarter – crowdfounding platforma"]),
                'params' => NULL,
                'sort_order' => 17,
                '_lft' => 9,
                '_rgt' => 10,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:05:40',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            19 =>
            array(
                'id' => 21,
                'slug' => 'tavariga',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "TavaRiga", "lv" => "TavaRiga"]),
                'description' => json_encode(["ru" => "TavaRiga - молодежное СМИ\r\nhttps://tavariga.lv/lv/", "lv" => "TavaRiga – jauniešu masu informācijas līdzeklis\r\nhttps://tavariga.lv/lv/"]),
                'params' => NULL,
                'sort_order' => 18,
                '_lft' => 11,
                '_rgt' => 12,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:05:49',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            20 =>
            array(
                'id' => 22,
                'slug' => 'voice_media',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Voice Media", "lv" => "Balss Media"]),
                'description' => json_encode(["ru" => "Voice Media - молодёжный журнал\\\\r\\\\nhttps:\\\\/\\\\/voicemedia.lv\\\\/", "lv" => "Balss Media - jaunatnes žurnāls\\\\r\\\\nhttps:\\\\/\\\\/voicemedia.lv\\\\/lv\\\\/"]),
                'params' => NULL,
                'sort_order' => 19,
                '_lft' => 13,
                '_rgt' => 14,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:06:03',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            21 =>
            array(
                'id' => 23,
                'slug' => 'nachat',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Начать", "lv" => "Sākt"]),
                'description' => json_encode(["ru" => "Какая возрастная категория вас интересует?", "lv" => "Kāda vecuma kategorija jūs interesē?"]),
                'params' => NULL,
                'sort_order' => 20,
                '_lft' => 1,
                '_rgt' => 60,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2022-09-23 20:08:44',
                'updated_at' => '2022-11-18 21:02:00',
            ),
            22 =>
            array(
                'id' => 24,
                'slug' => 'uznat_bolshe',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Узнать больше", "lv" => "Uzzināt vairāk"]),
                'description' => json_encode(["ru" => "Участие в клубе стоит 15 евро в месяц. \r\n\r\nЗа 15 евро в месяц вы получаете: \r\n\r\nИспользование наших офисов и художественной мастерской для своих целей (выполнение домашних заданий, встречи с друзьями) \r\n\r\nМногочисленные встречи, поддержку, помощь в написании проектов, менторскую программу от старших ребят.\r\n\r\nВстречи клубов по интересам.\r\n\r\nЛитературный клуб \r\nhttps://forms.gle/jJVQDj9pyJadpCMC7\r\n\r\nАниме клуб\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSf9NVzhe3zV_8DFIPmcTBzmDHWDTJAZ6TGTfP5M9ce4AVQ5ug/viewform\r\n\r\nКлуб японского\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSciuClqfpScwLvI6K67qOlwEJ0HRwLlfwSl3iHpqEnhVXkg0A/viewform\r\n\r\nКлуб немецкого языка \r\nej.uz/deutsch_YF\r\n\r\nПисательский клуб\r\nej.uz/pisateljstvo\r\n\r\nКиноклуб\r\nej.uz/YFkinoklub\r\n\r\nКлуб корейского\r\nhttps://forms.gle/SvtNhCtTH56Kywbo8\r\n\r\nКлуб настольных игр\r\nej.uz/YFnastolki\r\n\r\nКлуб собачников\r\nt.me/yfdogs\r\n\r\nКлуб по Dungeons & Dragons (DnD) \r\n\r\nКлуб английского\r\nej.uz/YFenglishclub", "lv" => "Dalība klubā maksā 15 eiro mēnesī.\r\n\r\nPar 15 eiro mēnesī jūs saņemat:\r\n\r\nMūsu biroju un mākslas darbnīcu izmantošanu savām vajadzībām (mājasdarbu veikšanai, tikšanos ar draugiem)\r\n\r\nDaudzus tikšanās, atbalstu, palīdzību projektu rakstīšanā, mentora programmu no vecākiem bērniem.\r\n\r\nKlubu tikšanās atbilstoši interesēm.\r\n\r\nLiteratūras klubs\r\nhttps://forms.gle/jJVQDj9pyJadpCMC7\r\n\r\nAnime klubs\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSf9NVzhe3zV_8DFIPmcTBzmDHWDTJAZ6TGTfP5M9ce4AVQ5ug/viewform\r\n\r\nJapāņu klubs\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSciuClqfpScwLvI6K67qOlwEJ0HRwLlfwSl3iHpqEnhVXkg0A/viewform\r\n\r\nVācu valodas klubs\r\nhttps://ej.uz/deutsch_YF\r\n\r\nRakstniecības klubs\r\nhttps://ej.uz/pisateljstvo\r\n\r\nKino klubs\r\nhttps://ej.uz/YFkinoklub\r\n\r\nKorejas klubs\r\nhttps://forms.gle/SvtNhCtTH56Kywbo8\r\n\r\nGalda spēļu klubs\r\nhttps://ej.uz/YFnastolki\r\n\r\nSuņu klubs\r\nhttps://t.me/yfdogs\r\n\r\nDungeons & Dragons (DnD) klubs\r\n\r\nAngļu valodas klubs\r\nhttps://ej.uz/YFenglishclub"]),
                'params' => NULL,
                'sort_order' => 21,
                '_lft' => 28,
                '_rgt' => 29,
                'parent_id' => 13,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 18:55:50',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            23 =>
            array(
                'id' => 25,
                'slug' => 'yf_travel',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "YF Travel", "lv" => "YF Ceļojumi"]),
                'description' => json_encode(["ru" => "С 2012 года мы с ребятами из Young Folks путешествуем по разным странам, в которых сами мечтали побывать с детства. Каждый год мы выезжаем более 15 раз за пределы Латвии и уже посетили такие страны и города как Израиль, Барселону, Исландию, Грузию, Францию, Англию, Данию, Санкт-Петербург и другие.\r\n\r\nЕсли хотите получать информацию о новых возможностях, заполняйте анкету: https://ej.uz/travellingYF", "lv" => "Kopš 2012. gada mēs kopā ar Young Folks ceļojam uz dažādām valstīm, kurās esam sapņojuši aizbraukt jau kopš bērnības. Katru gadu mēs braucam vairāk nekā 15 reizes ārpus Latvijas un esam apmeklējuši tādas valstis un pilsētas kā Izraēla, Barselona, Islande, Gruzija, Francija, Anglija, Dānija, Sanktpēterburga un citas.\r\n\r\nJa vēlaties saņemt informāciju par jaunajām iespējām, aizpildiet anketu: https://ej.uz/travellingYF"]),
                'params' => NULL,
                'sort_order' => 3,
                '_lft' => 31,
                '_rgt' => 32,
                'parent_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 18:58:43',
                'updated_at' => '2023-03-06 21:21:00',
            ),
            24 =>
            array(
                'id' => 26,
                'slug' => 'erasmus-podrostki-nachat',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Erasmus+", "lv" => "Erasmus+"]),
                'description' => json_encode(["ru" => "Erasmus+ написание проектов\r\n\r\nhttps://forms.gle/1KVQ6CYpsKu9f8bD8", "lv" => "Erasmus+ projektu rakstīšana\r\n\r\nhttps://forms.gle/1KVQ6CYpsKu9f8bD8"]),
                'params' => NULL,
                'sort_order' => 4,
                '_lft' => 33,
                '_rgt' => 34,
                'parent_id' => 3,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 18:59:15',
                'updated_at' => '2023-03-06 21:20:56',
            ),
            25 =>
            array(
                'id' => 27,
                'slug' => 'uznat_bolshe_2',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Узнать больше", "lv" => ""]),
                'description' => json_encode(["ru" => "Участие в клубе стоит 15 евро в месяц. \r\n\r\nЗа 15 евро вы получаете: \r\n\r\nИспользование наших офисов и художественной мастерской для своих целей (выполнение домашних заданий, встречи с друзьями) \r\n\r\nМногочисленные встречи, поддержку, помощь в написании проектов, мотивацию.\r\n\r\nВстречи клубов по интересам. \r\n\r\nДействующие клубы для подростков и молодежи:\r\n\r\nКлуб PhotOn - создание фотографии \r\nhttps://ej.uz/youngfolks_PhotOn\r\n\r\nЛитературный клуб \r\nhttps://forms.gle/jJVQDj9pyJadpCMC7\r\n\r\nАниме клуб\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSf9NVzhe3zV_8DFIPmcTBzmDHWDTJAZ6TGTfP5M9ce4AVQ5ug/viewform\r\n\r\nКлуб японского\r\nhttps://docs.google.com/forms/d/e/1FAIpQLSciuClqfpScwLvI6K67qOlwEJ0HRwLlfwSl3iHpqEnhVXkg0A/viewform\r\n\r\nКлуб немецкого языка \r\nhttps://ej.uz/deutsch_YF\r\n\r\nПисательский клуб\r\nhttps://ej.uz/pisateljstvo\r\n\r\nКиноклуб\r\nhttps://ej.uz/YFkinoklub\r\n\r\nКлуб корейского\r\nhttps://forms.gle/SvtNhCtTH56Kywbo8\r\n\r\nКлуб настольных игр\r\nhttps://ej.uz/YFnastolki\r\n\r\nКлуб собачников\r\nhttps://t.me/yfdogs\r\n\r\nКлуб по Dungeons & Dragons (ДнД) \r\n\r\nКлуб ментального здоровья\r\nhttps://t.me/+s2IxsIa7KgtjMTQ0\r\n\r\nИнициатива английского ProTalk\r\nhttps://forms.gle/o88TpgEKymp2sH3D6\r\n\r\nКлуб разработки игр\r\nhttps://ej.uz/youngfolks_studios\r\n\r\nБизнес-клуб\r\nhttps://youngfolks.lv/ru/rybc", "lv" => ""]),
                'params' => NULL,
                'sort_order' => 24,
                '_lft' => 53,
                '_rgt' => 54,
                'parent_id' => 4,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 19:00:48',
                'updated_at' => '2023-03-07 12:33:03',
            ),
            26 =>
            array(
                'id' => 28,
                'slug' => 'hochu_pomoch_young',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Хочу помочь Young Folks.", "lv" => "Gribu palīdzēt Jaunajiem."]),
                'description' => json_encode(["ru" => "Наша организация всегда рада видеть активистов и лидеров, которые готовы заниматься и развиваться в тех направлениях, которые им интересны. \r\n\r\nВы можете предложить свои услуги в проведении своего клуба по интересам/занятий; помощь с бухгалтерией; организацией мероприятий и прочего. \r\n\r\nЧтобы предложить свою идею/услугу, просим заполнить анкету ниже:\r\nhttps://forms.gle/59KFtHuCv3fLQA5g7", "lv" => "Mūsu organizācija vienmēr ir priecīga redzēt aktīvistus un līderus, kuri ir gatavi nodarboties un attīstīties tajos virzienos, kas tiem interesē. \r\n\r\nJūs varat piedāvāt savus pakalpojumus savu intereses kluba organizēšanā / nodarbību veikšanā; palīdzību grāmatvedības jomā; pasākumu organizēšanā un citiem uzdevumiem. \r\n\r\nLai piedāvātu savu ideju / pakalpojumu, lūdzu, aizpildiet anketu zemāk: \r\nhttps://forms.gle/59KFtHuCv3fLQA5g7"]),
                'params' => NULL,
                'sort_order' => 57,
                '_lft' => 58,
                '_rgt' => 4,
                'parent_id' => NULL,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 19:03:09',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            27 =>
            array(
                'id' => 29,
                'slug' => 'soyf',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "SOYF", "lv" => "SOYF"]),
                'description' => json_encode(["ru" => "Музыкальная группа", "lv" => "Mūzikas grupa"]),
                'params' => NULL,
                'sort_order' => 26,
                '_lft' => 15,
                '_rgt' => 16,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 20:10:01',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            28 =>
            array(
                'id' => 30,
                'slug' => 'karton',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "KARTON", "lv" => "KARTONS"]),
                'description' => json_encode(["ru" => "KARTON - художественная студия\\\\r\\\\nhttps://youngfolks.lv/karton", "lv" => "KARTONS - mākslas studija\\\\r\\\\nhttps://youngfolks.lv/karton"]),
                'params' => NULL,
                'sort_order' => 27,
                '_lft' => 17,
                '_rgt' => 18,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 20:10:27',
                'updated_at' => '2023-03-06 21:18:50',
            ),
            29 =>
            array(
                'id' => 31,
                'slug' => 'sporta_draugi',
                'enabled' => 1,
                'type_id' => 3,
                'name' => json_encode(["ru" => "Sporta draugi", "lv" => "Sporta draugi"]),
                'description' => json_encode(["ru" => "Sporta draugi - спортивный проект", "lv" => "Sporta draugi - sporta projekts"]),
                'params' => NULL,
                'sort_order' => 28,
                '_lft' => 19,
                '_rgt' => 20,
                'parent_id' => 5,
                'deleted_at' => NULL,
                'created_at' => '2022-10-19 20:10:53',
                'updated_at' => '2023-03-06 21:18:50',
            ),
        ));
    }
}
